### ISSUE TITLE
Can`t login on the website in subdirectory

### ISSUE THREAD

**Issue by Neolot** [manzoorwanijk/wptelegram-login#2]
Hi!
There's a problem with login on the website subdirectory, URL is invalid and return "File not found".
I fixed it in the file: wptelegram-login/public/class-wptelegram-login-public.php (row 577)
`$callback_url = add_query_arg( $args, home_url() );`
Can you check it and update the plugin?
Thanks!

**Comment by manzoorwanijk** [comment]
Thank you for reporting :)
